### ISSUE TITLE
Question about deauther/installation/compiling.md

### ISSUE THREAD

**Issue by slothstronomic** [SpacehuhnTech/wiki#9]
I have a question regarding the information on the [Wiki](https://spacehuhn.wiki/deauther/installation/compiling.md) at `deauther/installation/compiling.md`

When I enter this link: https://raw.githubusercontent.com/wiki/tobozo/Arduino/package_deauther_index.json in additional boards, the boards that I am supposed to download do not appear in the boards manager.

**Comment by spacehuhn** [comment]
Hi, thanks for the info. Seems to be an outdated URL. 
The correct one is:
`https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json`
